### ISSUE TITLE
Remove DenomUpsertTask and IBCDenomUpsertTask from main process

### ISSUE THREAD

**Issue by danbryan** [DefiantLabs/cosmos-tax-cli#373]
Lets decouple the Upsert Tasks from the main process, instead, create 2 new commands

cosmos-tax-cli **update-denoms**
cosmos-tax-cli **update-ibc-denoms**

To update the metadata we will create a cronjob on the cluster to handle keeping the metadata updated.

```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-metadata
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: update-metadata
            image: ghcr.io/defiantlabs/cosmos-tax-cli:main
            imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              cp /config/config.toml /home/defiant/
              cosmos-tax-cli update-denoms
              cosmos-tax-cli update-ibc-denoms
          restartPolicy: OnFailure
```
